import type { Metadata } from "next";
import { Navbar1 } from "@/components/navbar1";
import { Footer7 } from "@/components/footer7";
import { BookADemo2 } from "@/components/book-a-demo2";
import LocationMap from "@/components/map-component";
import { Hero3 } from "@/components/hero3";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
          
            {/* ============= Main Content ============== */}
            {children}

            
        </>
    );
}
